### PR TITLE
Accept html tags and entities in fake-area.

### PR DESCRIPTION
**Pull request by anaidenko**

### CODE REVIEW

**Review by aurbano — APPROVED** [review]
Thanks for the changes!

**Comment by anaidenko** [comment]
@aurbano I just realized your library is independent from jquery, let me rewrite htmlEncode to pure javascript in a moment.

**Comment by anaidenko** [comment]
@aurbano done, please merge https://github.com/aurbano/smart-area/pull/37 in

**Comment by aurbano** [comment]
@anaidenko good point, I didn't even realise when going through the other PR! Merged 👍

**Pull request merged**
